### ISSUE TITLE
Get Polo data since March 1, 2017

### ISSUE THREAD

**Issue by tomcounsell** [IntelligentTrading/core#15]
Check the Poloniex API for how we can download historical price data.

If we can get this data, we can run our indicators on them and see when signals would have been sent, then analyze how accurate our signals are.

https://poloniex.com/support/api/

**Comment by alexaibio** [comment]
done and pushed as follows:
- get the list of all possible pairs from https://poloniex.com/public?command=return24hVolume, ~70 pairs
- get historical data from https://poloniex.com/public?command=returnChartData,  ~30M per pair
- run as a django command   python manage.py hist_poloniex

Note:
- the whole imported data will take more then 1 GB of DB space and take a substantial time to process (for one pair ~ 3-4 min on my laptop x 70 pairs)
- when run a second time, records are not duplicated (unique index on (coin,timestamp) was added)
