### ISSUE TITLE
add more alt coins to signal sender

### ISSUE THREAD

**Issue by tomcounsell** [IntelligentTrading/core#34]
discuss with Vinnie to determine the list of coins we want to send signals for.

currently the setting is 

```
COINS_LIST = ["ETH", "XRP", "LTC", "DASH", "NEO", "XMR", "OMG"]
```

as seen in settings/__init__.py

**Comment by alexaibio** [comment]
Vinnie claim that this list of altcoins is enough...

**Comment by tomcounsell** [comment]
This is already done
