### ISSUE TITLE
Collect and save data from Poloniex every minute

### ISSUE THREAD

**Issue by tomcounsell** [IntelligentTrading/core#5]
User Story Link: https://trello.com/c/Lx4iyOey/30-poloniex

# Description and Context

We want to use Poloniex pricing and volume data on all coins tradable with BTC. The goal here is to collect the latest data every minute and store in a database where we can query large amounts for analysis

This data is the root source for every trade signal our services produces for trading crypto on Poloniex. If this process goes down, the entire service will go down so failover will also need to be in place.

# Possible Implementation

Create a scheduled task that runs every 60 seconds.

Get latest price and volume data on all coins trade-able with BTC (eg. BTC_ETH, BTC_OMG, etc)
URL = https://poloniex.com/public?command=returnTicker

Save the response data in json format in Google Cloud Datastore 

```
{
'channel': 'Poloniex',
'type': 'exchange'
'data': json_data,
'timestamp': int(timestamp_unix_seconds)
}
```

# Environment (REVIEW #13)

1.  Worker on App Engine: This worker is scheduled to get data **every minute** 

2.  Datastore NoSQL database: Store each request (moved to BigTable)

If the channel doesn't work, skip and do not store anything, but log an alert for possible fix needed if repeated.

**Comment by firemanxbr** [comment]
#12 first push to define what the best way to collect data from Poloniex to BigTable.

**Comment by firemanxbr** [comment]
#12 handle json/dictionaries between Poloniex and BigTable

**Comment by firemanxbr** [comment]
$ date ; python poloniex.py > [poloniex_output.txt](https://github.com/IntelligentTrading/data-sources/blob/issue5/bigtable/poloniex_output.txt) ; date
Wed Oct  4 03:27:56 +07 2017
Wed Oct  4 03:28:05 +07 2017

$ cbt lookup channels poloniex#1507062479 > [bigtable_output.txt](https://github.com/IntelligentTrading/data-sources/blob/issue5/bigtable/bigtable_output.txt)
